import pandas as pd

ventas = pd.read_csv('freshmart_datasets\campana_verano_ventas.csv')

print("=" * 60)
print("VENTAS DE LA CAMPAÑA")
print("=" * 60)
print(f"Filas Ventas: {len(ventas)}")
print()
print(f"Columnas ventas: {ventas.shape[1]}")
print()
print(ventas.dtypes)
print()
print("Primeras filas")
print()
print(ventas.head(10).to_string())
print()
print("Cantidad de nulos por columna")
print()
print(f"{ventas.isnull().sum()}")
print()
# Verifica formato de fecha
print("Muestras de fecha_compra: ")
print(ventas['fecha_compra'].sample(10, random_state=43).values)
print()
# verifica formato precio
print('Muestras de precio')
print(ventas['precio'].sample(10, random_state=42).values)
print()
print('Cantidad filas duplicadas: ')
print(ventas.duplicated().sum())
print()
print('Filas con cantidad de venta 0: ')
print(len(ventas[ventas['cantidad'] == 0]))
